filmbuzz/urls.py
from django.urls import path
from . import views
app_name = 'filmbuzz'

urlpatterns = [
    path('', views.index, name='index'),
    path('film/<int:film_id>/', views.detail, name='detail'),
    path('add/', views.add_film, name='add_film'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')

]

filmproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filmbuzz.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filmbuzz/models.py
from django.db import models

# Create your models here.
class Film(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

filmbuzz/forms.py
from django import forms
from.models import Film

class FilmForm(forms.ModelForm):
    class Meta:
        model = Film
        fields = ['name', 'description', 'year','img']

filmbuzz/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Film
from .forms import FilmForm


# Create your views here.
def index(request):
    film = Film.objects.all()
    context = {
        'film_list': film
    }
    return render(request, "index.html", context)


def detail(request, film_id):
    film = Film.objects.get(id=film_id)
    return render(request, 'detail.html', {'film': film})


def add_film(request):
    if request.method == 'POST':
        name = request.POST.get('name', )
        description = request.POST.get('description', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        film = Film(name=name, description=description, year=year, img=img)
        film.save()
    return render(request, 'add.html')


def update(request, id):
    film = Film.objects.get(id=id)
    form = FilmForm(request.POST or None, request.FILES, instance=film)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'film':film})


def delete(request,id):
    if request.method == 'POST':
        film = Film.objects.get(id=id)
        film.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
<input type="text" name="name" placeholder="Enter your film name">
<input type="text" name="description" placeholder="Enter the film description">
<input type="text" name="year" placeholder="Enter your film year">
<input type="file" name="img">
<input type="Submit">
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
<!-- Just an image -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
  FilmbuzZ.in
  <a href="/add/"><button>Add Film</button></a>
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    Do you want to delete this movie?
    <br>
    <input type="submit" value="Yes">
    <input type="submit" value="No">
</form>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
<div class="row">
    <div class="col-md-6">
    <img src="{{ film.img.url }}" style="width: 200px; height: 300px; object-fit: cover;">
    </div>
    <div class="col-md-6">
        <h4>{{ film.name }}</h4>
        <h6>({{ film.year }})</h6>
        <h6>{{ film.description }}</h6>
        <a class="btn btn-warning" href="{% url 'filmbuzz:update' film.id %}">Update</a>
        <a class="btn btn-danger" href="{% url 'filmbuzz:delete' film.id %}">Delete</a>
    </div>
</div>
</div>
{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
<div class="row">
    {% for i in film_list %}
    <div class="col-md-3">
    <div class="card" style="width: 100%; height: 15vw; object-fit: cover;">
    <img class="card-img-top" src="{{ i.img.url }}" alt="Card image cap" width="150px" height="300px" >
    <div class="card-body">
    <h5 class="card-title" style="font-size:12px;">{{ i.name }}</h5>
    <a href="{% url 'filmbuzz:detail' i.id %}" class="btn btn-primary">View</a>
    </div>
</div>
    </div>
    {% endfor %}
</div>
</div>

{% endblock %}